name: bdms_nest

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bdms_api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    command: sh -c "./node_modules/.bin/prisma migrate deploy && node dist/src/main.js"
